### ISSUE TITLE
DLL freezes on latest 9.0.7 release

### ISSUE THREAD

**Issue by zactrack-dev** [mvrdevelopment/libMVRgdtf#48]
**Describe the bug**
Buildling a Lib file on Windows and creating a subsequent DLL from a Cmake project, that statically links that Lib, a process that is loading the DLL gets stuck without output. 

**To Reproduce**
1. Build the Lib on Windows using the BAT script: "buildLib_Win.bat Release MD MZ false"
2. Create a simple Cmake Project and link the Lib (and add includes)
3. Write a small test routine, e.g. calling the QueryLocalServices() in the main() method 
4. Build an EXE out of it -> it works
5. Build a DLL that exports e.g. said QueryLocalServices() method -> any process loading that DLL will freeze

**Expected behavior**
DLL shall load without issue. No problems with version 9.0.6

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Visual Studio 2022 Community

**Additional context**
I was able to boil down the problem to the changes made in CMVRxchangeService.h/.cpp, which seem to fix stability issues when repeatedly creating and stopping local services. When building the EXE as mentioned above, it works as expected and the stability issues are gone.
I am lacking knowledge of the mechanics behind DLLs. Why are processes freezing already at DLL loading stage without calling any code from it?

**Comment by stephezapo** [comment]
Any updates on this? I was trying to fix it myself, because it looks easy on the first glance, but no luck so far :-(

**Comment by moritzstaffel** [comment]
We are looking into this and there will be a fix soon.

**Comment by stephezapo** [comment]
Hello!
Any news on this? I see that there were 2 releases recently without changes on the xchange side. Is the problem reproducable on your side?

**Comment by pwinkler-ds** [comment]
Hello @zactrack-dev,

I was not able to reproduce this issue with v9.0.7, can you share the zipped projectfiles here so we can test it with the same setup.

regards,
Patrick

**Comment by stephezapo** [comment]
Hello @pwinkler-ds !
Thanks a lot for getting back on this.
I sent a mail to @moritzstaffel with a zipped cmake project to reproduce the issue using the latest 9.0.11

Kind regards,
Stephan

**Comment by pwinkler-ds** [comment]
@stephezapo  Thanks for your mail.

Using a shared pointer for asio:deadlock solves the problem on my side, we will update this soon.

It is not recommended to define objs in global space especially in DLL's.

The easiest solution is to put the global **MVRService** object into a wrapper so it does not get initialized before the dll loading lock is released. 

```
static MVRService& getMvrService()
{
    static MVRService singleServiceInstance; // Gets only initialized on first call.
    return singleServiceInstance;
}

// Example call
getMvrService().queryServices();

```

**Comment by stephezapo** [comment]
@pwinkler-ds Thanks a lot for the helpful hint and sorry for the delay!
