### ISSUE TITLE
XMLCh and TXString cannot compute with each other

### ISSUE THREAD

**Issue by yoyo201626** [mvrdevelopment/libMVRgdtf#49]
**Describe the bug**
No calculations can be performed between **XMLCh** and **TXString**.

**To Reproduce**
1. Development environment:  **Windows10 19045.4412**, **cmake 3.29.2**, **Visual Studio Community 2022 17.9.5**
2. use cmake and then open visual studio
![image](https://github.com/mvrdevelopment/libMVRgdtf/assets/104079404/16fc477b-f409-443b-a6d5-fb98b05c2048)
3. compiling the MvrGdtf project
![image](https://github.com/mvrdevelopment/libMVRgdtf/assets/104079404/bd694f3c-08d5-4474-8a39-8ffec862efa6)
4. error occurs
![image](https://github.com/mvrdevelopment/libMVRgdtf/assets/104079404/a6592bf4-ec02-480f-84c1-0d331b9c0286)
![image](https://github.com/mvrdevelopment/libMVRgdtf/assets/104079404/0f29a82f-d600-465e-83ce-15d96a981060)

**Expected behavior**
no error occurs 

**Screenshots**
![image](https://github.com/mvrdevelopment/libMVRgdtf/assets/104079404/cdaffce9-5aa6-4791-bd72-53cb84feb68a)

**Desktop (please complete the following information):**
OS: Windows10 19045.4412
Visual Studio Community 2022  17.9.5
cmake 3.29.2

**Additional context**
I'm new to learning c++ and I'm sorry if my question is too superficial to trouble you

**Comment by moritzstaffel** [comment]
You need to define `-Dxmlch-type=wchar_t` for CMAKE. This should fix it. This is for the xerces build.

Otherwise you can use rapid XML. There is a a flag for this: `-DDONT_USE_XERCES_AS_XMLLIB=TRUE` this is for the actual libary.
