### ISSUE TITLE
Unexpected function in IGdtfCRI and IGdtfCRIGroup

### ISSUE THREAD

**Issue by AndriiVoitenko** [mvrdevelopment/libMVRgdtf#56]
**Describe the bug**
According to GDTF specification version 1.2 Color Rendering Index Group and Color Rendering Index does not have attribute Name. Nevertheless IGdtfCRIGroup and IGdtfCRI have function GetName(). And even there is no implementation for those function in CGdtfCRIGroupImpl and CGdtfCRIGroupImpl still those function could be confusing for library users. 

**To Reproduce**
Check the files
src\Include\IMediaRessourceVectorInterface.h starting from line 1407
src\Implementation\CGdtfCRIGroup.h
src\Implementation\CGdtfCRI.h

**Expected behavior**
there should not be Function GetName in interfaces

**Screenshots**
![1](https://github.com/user-attachments/assets/c14ff98e-d737-4635-9363-7059587dfce1)
![2](https://github.com/user-attachments/assets/a2c7f96b-426f-4fd8-bad6-2f46fed51f5f)

**Comment by adragnevVW** [comment]
Issue fixed in PR #59
